spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/wetender
    username: root
    password: 111111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

cocktailFile:
  dir: C:/images/cocktail/

liquorFile:
  dir: C:/images/liquor/

ingredientFile:
  dir: C:/images/ingredient/